package com.sdms.scheme.service;

import com.sdms.common.exception.ResourceNotFoundException;
import com.sdms.scheme.dto.SchemeCreateRequest;
import com.sdms.scheme.dto.SchemeResponse;
import com.sdms.scheme.entity.Scheme;
import com.sdms.scheme.repository.SchemeRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
public class SchemeService {

    private final SchemeRepository schemeRepository;

    public SchemeResponse createScheme(SchemeCreateRequest request){
        Scheme scheme = mapToEntity(request); // Before saving, scheme.id is null (no id yet, DB hasn't touched it).
        Scheme saved = schemeRepository.save(scheme); // when save is called, then only id is generated by mysql and hibernate gives it back to us, and we are storing this in a "saved" variable.... Now this variable has id and isActive fields, so we finaly return this object not the initial one which we took form scheme create request
        return mapToResponse(saved);
    }

    public List<SchemeResponse> getAllActiveSchemes(){
        List<Scheme> schemes = schemeRepository.findByIsActiveTrue();
        return schemes.stream().map(this::mapToResponse).toList();
    }

    public SchemeResponse getSchemeById(Long id){
        Scheme scheme = schemeRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Scheme not found with id: " + id));
        return mapToResponse(scheme);
    }

    public List<SchemeResponse> getSchemesByRegion(String region){
        List<Scheme> schemes = schemeRepository.findByRegion(region);
        return schemes.stream().map(this::mapToResponse).toList();
    }

    // for updating also, we assign values to the same fields as when we create a scheme, so we can use the createScheme DTO only
    public SchemeResponse updateScheme(Long id, SchemeCreateRequest request){
        Scheme scheme = schemeRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Scheme not found with id: " + id));
        scheme.setName(request.getName());
        scheme.setDescription(request.getDescription());
        scheme.setMinIncome(request.getMinIncome());
        scheme.setMaxIncome(request.getMaxIncome());
        scheme.setGrantAmount(request.getGrantAmount());
        scheme.setRegion(request.getRegion());
        scheme.setTotalBudget(request.getTotalBudget());
        Scheme saved = schemeRepository.save(scheme);
        return mapToResponse(saved);
    }

    public void deactivateScheme(Long id){
        Scheme scheme = schemeRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Scheme not found with id: " + id));
        scheme.setIsActive(false);
        schemeRepository.save(scheme);
    }

    public void activateScheme(Long id){
        Scheme scheme = schemeRepository.findById(id).orElseThrow(() -> new ResourceNotFoundException("Scheme not found with id: " + id));
        scheme.setIsActive(true);
        schemeRepository.save(scheme);
    }

    private Scheme mapToEntity(SchemeCreateRequest request){
        Scheme scheme = new Scheme();
        scheme.setName(request.getName());
        scheme.setDescription(request.getDescription());
        scheme.setMinIncome(request.getMinIncome());
        scheme.setMaxIncome(request.getMaxIncome());
        scheme.setGrantAmount(request.getGrantAmount());
        scheme.setRegion(request.getRegion());
        scheme.setTotalBudget(request.getTotalBudget());
        return scheme;
    }

    private SchemeResponse mapToResponse(Scheme scheme){
        return new SchemeResponse(
                scheme.getId(),
                scheme.getName(),
                scheme.getDescription(),
                scheme.getMinIncome(),
                scheme.getMaxIncome(),
                scheme.getGrantAmount(),
                scheme.getRegion(),
                scheme.getTotalBudget(),
                scheme.getIsActive()
        );
    }
}
