package com.sdms.audit.entity;

public enum AuditAction {
    APPLICATION_FIELD_VERIFIED,
    APPLICATION_DISTRICT_VERIFIED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,

    DISBURSEMENT_RELEASED,
    DISBURSEMENT_MARKED_FAILED,
    DISBURSEMENT_RETRIED,

    USER_CREATED,
    USER_ACTIVATED,
    USER_DEACTIVATED,

    BENEFICIARY_CREATED,
    BENEFICIARY_UPDATED,
    BENEFICIARY_ACTIVATED,
    BENEFICIARY_DEACTIVATED
}